/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Daniel
 */
public class CalculadoraFisica extends javax.swing.JFrame {
    
    // Variáveis globais
    int auxiliar = 0;
    double resultado = 0;
    FormulasFisicaCalculo fisica = new FormulasFisicaCalculo();
    ResultadoFormulaFisica resultados = new ResultadoFormulaFisica();
    
    /**
     * Creates new form CalculadoraFisica
     */
    public CalculadoraFisica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        inputTextFirst = new javax.swing.JTextPane();
        forca = new javax.swing.JButton();
        tituloCalculadora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        resultadoCalculo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputTextSecond = new javax.swing.JTextPane();
        aceleracao = new javax.swing.JButton();
        massa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        inputTextFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(inputTextFirst);

        forca.setText("Força");
        forca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forcaActionPerformed(evt);
            }
        });

        tituloCalculadora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCalculadora.setText("Calculadora de física");

        jLabel2.setText("Digite o valor: ");

        jLabel3.setText("Digite o valor: ");

        jButton4.setText("Calcular");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        resultadoCalculo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        resultadoCalculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoCalculo.setText("0,00");

        inputTextSecond.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(inputTextSecond);

        aceleracao.setText("Aceleracao");
        aceleracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceleracaoActionPerformed(evt);
            }
        });

        massa.setText("Massa");
        massa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                massaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(tituloCalculadora)
                        .addGap(86, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(massa)
                        .addGap(92, 92, 92)
                        .addComponent(forca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceleracao)))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultadoCalculo)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCalculadora)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forca)
                    .addComponent(massa)
                    .addComponent(aceleracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(resultadoCalculo)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void massaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_massaActionPerformed
        // TODO add your handling code here:
        
        jLabel2.setText("Digite a Forca (N): ");
        jLabel3.setText("Digite a Aceleracao (m/s²): ");
        
        auxiliar = 1;
    }//GEN-LAST:event_massaActionPerformed

    private void forcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forcaActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("Digite a Massa (kg): ");
        jLabel3.setText("Digite a Aceleracao (m/s²): ");
        
        auxiliar = 2;
    }//GEN-LAST:event_forcaActionPerformed

    private void aceleracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceleracaoActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("Digite a Forca (N): ");
        jLabel3.setText("Digite a Massa (kg): ");
        
        auxiliar = 3;
    }//GEN-LAST:event_aceleracaoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Atribuir variaveis
        double resultFirst = Double.parseDouble(inputTextFirst.getText());
        double resultSecond = Double.parseDouble(inputTextSecond.getText());
        
       switch(auxiliar){
            case 1:
                // calculo da massa
                fisica.setForca(resultFirst);
                fisica.setAceleracao(resultSecond);
                
                resultadoCalculo.setText(""+ resultados.resultadoMassa() + " kg");
            break;
            
            case 2:
                // calculo da forca
                fisica.setMassa(resultFirst);
                fisica.setAceleracao(resultSecond);
                
                resultadoCalculo.setText(""+ resultados.resultadoForca() + " N");
            break;
            
            case 3:
                //Calculo aceleracao
                fisica.setForca(resultFirst);
                fisica.setMassa(resultSecond);
                
                resultadoCalculo.setText(""+ resultados.resultadoAceleracao() + " m/s²");
            
            break;
                
            default:
                System.out.println("Nada encontrado");
            break;
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFisica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceleracao;
    private javax.swing.JButton forca;
    private javax.swing.JTextPane inputTextFirst;
    private javax.swing.JTextPane inputTextSecond;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton massa;
    private javax.swing.JLabel resultadoCalculo;
    private javax.swing.JLabel tituloCalculadora;
    // End of variables declaration//GEN-END:variables
}
